CREATE TYPE "Role" AS ENUM ('SUPER_ADMIN', 'PROPERTY_MANAGER', 'ACCOUNTANT', 'MAINTENANCE_MANAGER', 'STAFF', 'TENANT');
CREATE TYPE "PropertyStatus" AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE "PropertyType" AS ENUM ('RESIDENTIAL', 'COMMERCIAL', 'MIXED', 'OTHER');
CREATE TYPE "UnitStatus" AS ENUM ('AVAILABLE', 'OCCUPIED', 'MAINTENANCE', 'INACTIVE');
CREATE TYPE "LeaseStatus" AS ENUM ('DRAFT', 'ACTIVE', 'EXPIRED', 'TERMINATED');
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'PAID', 'OVERDUE', 'CANCELLED');
CREATE TABLE "User" ("id" TEXT NOT NULL,"name" TEXT,"email" TEXT,"emailVerified" TIMESTAMP(3),"image" TEXT,"password" TEXT NOT NULL,"role" "Role" NOT NULL DEFAULT 'STAFF',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE TABLE "Property" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"address" TEXT NOT NULL,"city" TEXT NOT NULL,"country" TEXT NOT NULL,"type" "PropertyType" NOT NULL DEFAULT 'RESIDENTIAL',"status" "PropertyStatus" NOT NULL DEFAULT 'ACTIVE',"managerId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Property_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Property_managerId_idx" ON "Property"("managerId"); CREATE INDEX "Property_status_idx" ON "Property"("status");
CREATE TABLE "Unit" ("id" TEXT NOT NULL,"propertyId" TEXT NOT NULL,"unitNumber" TEXT NOT NULL,"floor" INTEGER,"bedrooms" INTEGER,"bathrooms" DOUBLE PRECISION,"area" DOUBLE PRECISION,"rentAmount" DOUBLE PRECISION NOT NULL,"status" "UnitStatus" NOT NULL DEFAULT 'AVAILABLE',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Unit_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Unit_propertyId_unitNumber_key" ON "Unit"("propertyId","unitNumber"); CREATE INDEX "Unit_status_idx" ON "Unit"("status");
CREATE TABLE "Tenant" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"email" TEXT,"phone" TEXT,"nationalId" TEXT,"address" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Tenant_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Tenant_email_idx" ON "Tenant"("email");
CREATE TABLE "Lease" ("id" TEXT NOT NULL,"unitId" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"startDate" TIMESTAMP(3) NOT NULL,"endDate" TIMESTAMP(3) NOT NULL,"rentAmount" DOUBLE PRECISION NOT NULL,"depositAmount" DOUBLE PRECISION,"paymentDueDay" INTEGER NOT NULL DEFAULT 1,"status" "LeaseStatus" NOT NULL DEFAULT 'DRAFT',"notes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Lease_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Lease_unitId_idx" ON "Lease"("unitId"); CREATE INDEX "Lease_tenantId_idx" ON "Lease"("tenantId"); CREATE INDEX "Lease_status_idx" ON "Lease"("status");
CREATE TABLE "Payment" ("id" TEXT NOT NULL,"leaseId" TEXT NOT NULL,"amount" DOUBLE PRECISION NOT NULL,"dueDate" TIMESTAMP(3) NOT NULL,"paidDate" TIMESTAMP(3),"status" "PaymentStatus" NOT NULL DEFAULT 'PENDING',"method" TEXT,"reference" TEXT,"notes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Payment_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Payment_leaseId_idx" ON "Payment"("leaseId"); CREATE INDEX "Payment_status_idx" ON "Payment"("status"); CREATE INDEX "Payment_dueDate_idx" ON "Payment"("dueDate");
CREATE TABLE "Expense" ("id" TEXT NOT NULL,"propertyId" TEXT NOT NULL,"unitId" TEXT,"category" TEXT NOT NULL,"amount" DOUBLE PRECISION NOT NULL,"date" TIMESTAMP(3) NOT NULL,"vendor" TEXT,"notes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Expense_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Expense_propertyId_idx" ON "Expense"("propertyId"); CREATE INDEX "Expense_unitId_idx" ON "Expense"("unitId"); CREATE INDEX "Expense_date_idx" ON "Expense"("date");
CREATE TABLE "MaintenanceRequest" ("id" TEXT NOT NULL,"propertyId" TEXT NOT NULL,"unitId" TEXT,"tenantId" TEXT,"assignedToId" TEXT,"title" TEXT NOT NULL,"description" TEXT,"priority" TEXT NOT NULL DEFAULT 'MEDIUM',"status" TEXT NOT NULL DEFAULT 'OPEN',"cost" DOUBLE PRECISION,"openedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"resolvedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "MaintenanceRequest_pkey" PRIMARY KEY ("id"));
CREATE INDEX "MaintenanceRequest_propertyId_idx" ON "MaintenanceRequest"("propertyId"); CREATE INDEX "MaintenanceRequest_unitId_idx" ON "MaintenanceRequest"("unitId"); CREATE INDEX "MaintenanceRequest_tenantId_idx" ON "MaintenanceRequest"("tenantId"); CREATE INDEX "MaintenanceRequest_assignedToId_idx" ON "MaintenanceRequest"("assignedToId"); CREATE INDEX "MaintenanceRequest_status_idx" ON "MaintenanceRequest"("status");
CREATE TABLE "Account" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"type" TEXT NOT NULL,"provider" TEXT NOT NULL,"providerAccountId" TEXT NOT NULL,"refresh_token" TEXT,"access_token" TEXT,"expires_at" INTEGER,"token_type" TEXT,"scope" TEXT,"id_token" TEXT,"session_state" TEXT,CONSTRAINT "Account_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Account_provider_providerAccountId_key" ON "Account"("provider","providerAccountId");
CREATE TABLE "Session" ("id" TEXT NOT NULL,"sessionToken" TEXT NOT NULL,"userId" TEXT NOT NULL,"expires" TIMESTAMP(3) NOT NULL,CONSTRAINT "Session_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Session_sessionToken_key" ON "Session"("sessionToken");
CREATE TABLE "VerificationToken" ("identifier" TEXT NOT NULL,"token" TEXT NOT NULL,"expires" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "VerificationToken_token_key" ON "VerificationToken"("token"); CREATE UNIQUE INDEX "VerificationToken_identifier_token_key" ON "VerificationToken"("identifier","token");
ALTER TABLE "Property" ADD CONSTRAINT "Property_managerId_fkey" FOREIGN KEY ("managerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Unit" ADD CONSTRAINT "Unit_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Lease" ADD CONSTRAINT "Lease_unitId_fkey" FOREIGN KEY ("unitId") REFERENCES "Unit"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Lease" ADD CONSTRAINT "Lease_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_leaseId_fkey" FOREIGN KEY ("leaseId") REFERENCES "Lease"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Expense" ADD CONSTRAINT "Expense_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Expense" ADD CONSTRAINT "Expense_unitId_fkey" FOREIGN KEY ("unitId") REFERENCES "Unit"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "MaintenanceRequest" ADD CONSTRAINT "MaintenanceRequest_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MaintenanceRequest" ADD CONSTRAINT "MaintenanceRequest_unitId_fkey" FOREIGN KEY ("unitId") REFERENCES "Unit"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "MaintenanceRequest" ADD CONSTRAINT "MaintenanceRequest_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "MaintenanceRequest" ADD CONSTRAINT "MaintenanceRequest_assignedToId_fkey" FOREIGN KEY ("assignedToId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
